webtalk_init -webtalk_dir /ad/eng/users/w/k/wkrska/Documents/EC551/EC551_Labs/Lab2/Unified Terminal Interface/Terminal_Interface/Terminal_Interface.sim/sim_1/behav/xsim/xsim.dir/test_data_loader_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Nov 10 03:43:16 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211078688_174135686_206649660_409" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "61835efa-6569-442e-ba2e-dddbe073e23a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "cea4847d71294ce09da085bb15d9b020" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "29" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "CentOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "CentOS Linux release 7.9.2009 (Core)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Xeon(R) CPU E5-2640 v4 @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "1299.902 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "67.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "6" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "89 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "8 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "45" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "14" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "2.31_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "317320_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2263888813 -regid "211078688_174135686_206649660_409" -xml /ad/eng/users/w/k/wkrska/Documents/EC551/EC551_Labs/Lab2/Unified Terminal Interface/Terminal_Interface/Terminal_Interface.sim/sim_1/behav/xsim/xsim.dir/test_data_loader_behav/webtalk/usage_statistics_ext_xsim.xml -html /ad/eng/users/w/k/wkrska/Documents/EC551/EC551_Labs/Lab2/Unified Terminal Interface/Terminal_Interface/Terminal_Interface.sim/sim_1/behav/xsim/xsim.dir/test_data_loader_behav/webtalk/usage_statistics_ext_xsim.html -wdm /ad/eng/users/w/k/wkrska/Documents/EC551/EC551_Labs/Lab2/Unified Terminal Interface/Terminal_Interface/Terminal_Interface.sim/sim_1/behav/xsim/xsim.dir/test_data_loader_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
