# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 3
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Terminal_Interface/Terminal_Interface.cache/wt} [current_project]
set_property parent.project_path {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Terminal_Interface/Terminal_Interface.xpr} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_repo_paths d:/WorkBORI/gpio/Nexys-A7/hw/repo [current_project]
update_ip_catalog
set_property ip_output_repo {c:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Terminal_Interface/Terminal_Interface.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog {{C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/my_header.vh}}
set_property file_type "Verilog Header" [get_files {{C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/my_header.vh}}]
read_verilog -library xil_defaultlib {
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/ALU.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/Decoder.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/Fetch_unit.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Terminal_Interface/Terminal_Interface.srcs/sources_1/new/PS2Receiver.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/Register_file.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/UART_RX_CTRL.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/alu_to_ascii.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/btn_edge.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/data_loader.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/datapath.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/debounce.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/hex_to_ascii.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Terminal_Interface/Terminal_Interface.srcs/sources_1/new/keyboard_debouncer.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/mat3mult.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/mat_to_ascii.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/memory.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/mini_ALU.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/ps2_to_ascii.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/reg_param.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Terminal_Interface/Terminal_Interface.srcs/sources_1/new/top_keyboard.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/uart_arbiter.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/vect3mac.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Sources/Design/vga.v}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Terminal_Interface/Terminal_Interface.srcs/sources_1/new/term_interf_top.v}
}
read_vhdl -library xil_defaultlib {
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Terminal_Interface/Terminal_Interface.srcs/sources_1/imports/hdl/UART_TX_CTRL.vhd}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Terminal_Interface/Terminal_Interface.srcs/sources_1/imports/hdl/debouncer.vhd}
  {C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Terminal_Interface/Terminal_Interface.srcs/sources_1/imports/hdl/top.vhd}
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Terminal_Interface/Terminal_Interface.srcs/constrs_1/imports/constraints/Nexys-A7-100T-Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Users/wkrska/Downloads/temp/EC551_Labs/Lab2/Unified Terminal Interface/Terminal_Interface/Terminal_Interface.srcs/constrs_1/imports/constraints/Nexys-A7-100T-Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top term_interf_top -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef term_interf_top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file term_interf_top_utilization_synth.rpt -pb term_interf_top_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
