webtalk_init -webtalk_dir X:/EC551/Labs/Lab1/Final Copy/EC551_Labs/lab_1/lab_1.sim/sim_1/behav/xsim/xsim.dir/t_VGA_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct 27 14:27:25 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211078688_174135686_206649660_409" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "e231ddc0-1cfe-4f97-a765-09b4bb903096" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "939031e321024f558539e0104ed568b1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7800X CPU @ 3.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3504 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "5000010 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "3.92_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "15200_KB" -context "xsim\\usage"
webtalk_transmit -clientid 911641815 -regid "211078688_174135686_206649660_409" -xml X:/EC551/Labs/Lab1/Final Copy/EC551_Labs/lab_1/lab_1.sim/sim_1/behav/xsim/xsim.dir/t_VGA_behav/webtalk/usage_statistics_ext_xsim.xml -html X:/EC551/Labs/Lab1/Final Copy/EC551_Labs/lab_1/lab_1.sim/sim_1/behav/xsim/xsim.dir/t_VGA_behav/webtalk/usage_statistics_ext_xsim.html -wdm X:/EC551/Labs/Lab1/Final Copy/EC551_Labs/lab_1/lab_1.sim/sim_1/behav/xsim/xsim.dir/t_VGA_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
