# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/wkrska/Downloads/temp labs/EC551_Labs/lab3/Sources/IP/ascii_char_fifo/ascii_char_fifo.xci
# IP: The module: 'ascii_char_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wkrska/Downloads/temp labs/EC551_Labs/lab3/Sources/IP/ascii_char_fifo/ascii_char_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'ascii_char_fifo'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/wkrska/Downloads/temp labs/EC551_Labs/lab3/Sources/IP/ascii_char_fifo/ascii_char_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ascii_char_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/wkrska/Downloads/temp labs/EC551_Labs/lab3/Sources/IP/ascii_char_fifo/ascii_char_fifo.xci
# IP: The module: 'ascii_char_fifo' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/wkrska/Downloads/temp labs/EC551_Labs/lab3/Sources/IP/ascii_char_fifo/ascii_char_fifo.xdc
# XDC: The top module name and the constraint reference have the same name: 'ascii_char_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# XDC: c:/Users/wkrska/Downloads/temp labs/EC551_Labs/lab3/Sources/IP/ascii_char_fifo/ascii_char_fifo_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ascii_char_fifo'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
